# https://taskfile.dev

version: "3"

vars:
  APP: app
  LIB: liba.a

tasks:
  default:
    cmds:
      - task: clean
      - task: build
      - task: verify
      - task: run
  run:
    cmds:
      - ./{{.APP}}
    env:
      LD_LIBRARY_PATH: .
  build:
    cmds:
      - go build -a -x -o {{.LIB}} -buildmode=c-archive main.go > out.txt 2>&1
      - gcc -g3 -O0 -Wall -Wextra -I. -L. -o {{.APP}} {{.APP}}.c -la
  verify:
    cmds:
      - nm ./{{.LIB}} | grep -F "T cgo_func"
      - nm ./{{.APP}} | grep -F "T cgo_func"
  clean:
    cmds:
      - rm -f {{.APP}} {{.LIB}}
